[tool.poetry]
name = "homework-1"
version = "0.1.0"
description = ""
authors = ["Ilia Kaziamov <teacher.ilya.255@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
